# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Quantitative Views
author: For any queries, comments or suggestions, please contact me
email: vlamb@duck.com
description: >- # this means to ignore newlines until "baseurl:"
  Any technology distinguishable from magic is insufficiently advanced.
baseurl: "" # the subpath of your site, e.g. /blog
# url: https://vikaslamba99.github.io
# github_username:  vikaslamba99
site:
    github_username:  vikaslamba99
    linkedin_username:  vikas-lamba-frm-24413644


# Build settings
theme: minima

minima:
  skin: dark
  date_format: "%Y-%m-%d %H:%M"
  site:
    github: vikaslamba99
    linkedin: taylor-talkinton
    gitlab:
      - username: The-EG
        instance: gitlab.com

# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/). 
# If you want to use the latest Minima version on GitHub Pages, use the following setting and 
# add a line comment on "theme: minima" above.
#remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
# Set to `true` to show excerpts on the homepage.
show_excerpts: true
# Build settings
